### PR TITLE
Feature/norminette sphere,plane

### PR DESCRIPTION
**Pull request by Shivalux**
- changed double to float.
- norminette was fixed, except parsing path.

### CODE REVIEW

**Comment by Shivalux** [comment]
hello, how are you today?

**Comment by viruskizz** [comment]
> hello, how are you today?

Relaxing

**Comment by Shivalux** [comment]
> > hello, how are you today?
> 
> Relaxing

solve

**Comment by viruskizz** [comment]
LGTM

**Review by viruskizz — APPROVED** [review]
Perfect

**Pull request merged**
