### PR TITLE
Feature/parsing and key

### PR DESCRIPTION
**Pull request by Shivalux**

### CODE REVIEW

**Comment by Shivalux** [comment]
not ready to merge just play around  pull request.

**Comment by Shivalux** [comment]
- changed t_lht to t_obj.
- added all transformation in element_key_transformation return to solving render every time.

**Review by viruskizz — COMMENTED** [review]
Thank you

**Comment by Shivalux** [comment]
separate lights and objects

**Review by viruskizz — APPROVED** [review]
LGTM

**Pull request merged**
