### PR TITLE
fix: panel-ui

### PR DESCRIPTION
**Pull request by viruskizz**

### CODE REVIEW

**Comment by Shivalux** [comment]
- render added.
- mouse_hook added.
- dynamic panel interface.
- data_initialise added.

- not norminette fix.
- not optimize.

**Comment by viruskizz** [comment]
> * render added.
> * mouse_hook added.
> * dynamic panel interface.
> * data_initialise added.
> 
> will continue do norminette fixed and optimize the same function.

If you done, pls let me know.

**Comment by Shivalux** [comment]
all done..
- optimized
- nominetted

**Comment by viruskizz** [comment]
GOOD

**Pull request merged**
